name: deploy to ftp server
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload FTP
      uses: genietim/ftp-action
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "pb_hooks"
        remoteDir: "justjot/pb_hooks"
